#!/usr/bin/env bash
# Highlander: There can be only one

# print I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"; sleep 2' SIGTERM


while true; do
    sleep 2
    echo "To infinity and beyond"
done
